### ISSUE TITLE
Remove "Recert" fields from SW document

### ISSUE THREAD

**Issue by dylan171** [frib-high-level-controls/swdb#21]
The "recertFreq", "recertStatus" and "recertDate" fields are not longer needed in the application. They should be removed from the database schema and the corresponding forms/views.

**Comment by rellis6022** [comment]
Merged in pull #30

**Comment by dylan171** [comment]
@rellis6022  The "Certification" header is still included on the software details page:

![screenshot_2018-05-22 swdb - details](https://user-images.githubusercontent.com/109703/40383576-3e8f0e8a-5dcf-11e8-8445-114ea1281fe3.png)

**Comment by dylan171** [comment]
Looks good.
